import React, { useState, useEffect, useRef } from "react";
import {
  Send,
  UploadCloud,
  FileText,
  MessageSquare,
  BarChart3,
  ChevronRight,
  Zap,
  Cpu,
  Clock,
  RefreshCw,
  Database,
  TrendingUp,
  DollarSign,
  ShieldCheck,
  Terminal,
} from "lucide-react";
import "./App.css";

const API_BASE = "http://localhost:8000";

function App() {
  const [query, setQuery] = useState("");
  const [messages, setMessages] = useState([
    {
      role: "assistant",
      content:
        "Welcome to AURA Gateway. Upload documents via the Explorer sidebar, then ask questions here. Responses are generated by Groq (Llama 3.1 8B) and audited by the Gemini Alignment Judge.",
      source: "system",
      latency_ms: 0,
      cache_similarity: 0,
      retrieved_chunks: [],
    },
  ]);
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [dragActive, setDragActive] = useState(false);
  const [documents, setDocuments] = useState([]);
  const [activeView, setActiveView] = useState("chat");
  const [activePanel, setActivePanel] = useState("metrics");
  const [metrics, setMetrics] = useState({
    summary: { total_queries: 0, cache_hits: 0, cache_misses: 0, cache_hit_ratio: 0.0, cached_items: 0 },
    llm_usage: { primary_input_tokens: 0, primary_output_tokens: 0, evaluator_input_tokens: 0, evaluator_output_tokens: 0, total_cost_usd: 0.0, saved_cost_usd: 0.0 },
    evaluation_metrics: { evaluations_count: 0, average_faithfulness: 0.0, average_relevance: 0.0, logs: [] },
    system_status: { simulation_mode: true, groq_active: false, gemini_active: false },
  });

  const chatEndRef = useRef(null);
  const fileInputRef = useRef(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, loading]);

  useEffect(() => {
    fetchDocuments();
    fetchMetrics();
    const interval = setInterval(fetchMetrics, 3000);
    return () => clearInterval(interval);
  }, []);

  const fetchDocuments = async () => {
    try {
      const r = await fetch(`${API_BASE}/api/documents`);
      if (r.ok) setDocuments(await r.json());
    } catch (e) { /* ignore */ }
  };

  const fetchMetrics = async () => {
    try {
      const r = await fetch(`${API_BASE}/api/metrics`);
      if (r.ok) setMetrics(await r.json());
    } catch (e) { /* ignore */ }
  };

  const handleFileUpload = async (file) => {
    if (!file) return;
    if (!file.name.endsWith(".pdf") && !file.name.endsWith(".txt")) {
      alert("Only PDF and TXT files are supported.");
      return;
    }
    setUploading(true);
    const fd = new FormData();
    fd.append("file", file);
    try {
      const r = await fetch(`${API_BASE}/api/upload`, { method: "POST", body: fd });
      const data = await r.json();
      if (r.ok) {
        fetchDocuments();
        fetchMetrics();
        setMessages((prev) => [...prev, {
          role: "assistant",
          content: `Indexed "${file.name}" → ${data.chunks_count} vector chunks stored in Qdrant.`,
          source: "system", latency_ms: 0, cache_similarity: 0, retrieved_chunks: [],
        }]);
      } else alert(`Upload failed: ${data.detail}`);
    } catch (e) { alert("Network error uploading document."); }
    finally { setUploading(false); }
  };

  const handleDrag = (e) => { e.preventDefault(); e.stopPropagation(); setDragActive(e.type === "dragenter" || e.type === "dragover"); };
  const handleDrop = (e) => { e.preventDefault(); e.stopPropagation(); setDragActive(false); if (e.dataTransfer.files?.[0]) handleFileUpload(e.dataTransfer.files[0]); };

  const handleSend = async (e) => {
    e.preventDefault();
    const text = query.trim();
    if (!text || loading) return;
    setQuery("");
    setMessages((prev) => [...prev, { role: "user", content: text }]);
    setLoading(true);
    try {
      const r = await fetch(`${API_BASE}/api/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query: text }),
      });
      const data = await r.json();
      if (r.ok) {
        setMessages((prev) => [...prev, {
          role: "assistant", content: data.answer, source: data.source,
          latency_ms: data.latency_ms, cache_similarity: data.cache_similarity,
          retrieved_chunks: data.retrieved_chunks, evaluation: data.evaluation,
        }]);
        fetchMetrics();
      } else {
        setMessages((prev) => [...prev, { role: "assistant", content: `Error: ${data.detail}`, source: "system", latency_ms: 0, cache_similarity: 0, retrieved_chunks: [] }]);
      }
    } catch (e) {
      setMessages((prev) => [...prev, { role: "assistant", content: "Network error reaching the gateway.", source: "system", latency_ms: 0, cache_similarity: 0, retrieved_chunks: [] }]);
    } finally { setLoading(false); }
  };

  const handleReset = async () => {
    if (!window.confirm("Reset all data, caches, and metrics?")) return;
    try {
      await fetch(`${API_BASE}/api/metrics/reset`, { method: "POST" });
      setMessages([{ role: "assistant", content: "System reset complete. All indexes, caches, and metrics cleared.", source: "system", latency_ms: 0, cache_similarity: 0, retrieved_chunks: [] }]);
      setDocuments([]);
      fetchMetrics();
    } catch (e) { /* ignore */ }
  };

  const renderGauge = (score, label, type) => {
    const r = 22, circ = 2 * Math.PI * r, offset = circ - score * circ;
    return (
      <div className="gauge-item">
        <div className="gauge-svg-container">
          <svg width="56" height="56">
            <circle className="gauge-bg" cx="28" cy="28" r={r} />
            <circle className={`gauge-fill ${type}`} cx="28" cy="28" r={r} strokeDasharray={circ} strokeDashoffset={offset} />
          </svg>
          <div className="gauge-text">{Math.round(score * 100)}%</div>
        </div>
        <span className="gauge-label">{label}</span>
      </div>
    );
  };

  const now = new Date();
  const timeStr = now.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });

  return (
    <div className="app-container">
      {/* Title Bar */}
      <div className="titlebar">
        <div className="titlebar-left">
          <div className="titlebar-icon"><Cpu size={14} /></div>
          <span className="titlebar-app-name">AURA</span>
        </div>
        <div className="titlebar-title">CachedRAG Cost-Optimized Document Intelligence Engine</div>
      </div>

      {/* Body */}
      <div className="app-body">
        {/* Activity Bar */}
        <div className="activity-bar">
          <button className={`activity-btn ${activeView === "chat" ? "active" : ""}`} title="Chat" onClick={() => setActiveView("chat")}>
            <FileText size={22} />
            {documents.length > 0 && <span className="activity-badge">{documents.length}</span>}
          </button>
          <button className={`activity-btn ${activeView === "metrics" ? "active" : ""}`} title="Analytics" onClick={() => setActiveView("metrics")}>
            <BarChart3 size={22} />
          </button>
        </div>

        {/* Sidebar */}
        <div className="sidebar">
          <div className="sidebar-header">Explorer</div>

          {/* Upload Section */}
          <div className="sidebar-section">
            <div className="sidebar-section-header">
              <ChevronRight size={12} /> Knowledge Base
            </div>
            <div className="sidebar-section-body">
              <div
                className={`upload-dropzone ${dragActive ? "dragging" : ""}`}
                onDragEnter={handleDrag} onDragOver={handleDrag} onDragLeave={handleDrag} onDrop={handleDrop}
                onClick={() => fileInputRef.current.click()}
              >
                <input type="file" ref={fileInputRef} onChange={(e) => e.target.files?.[0] && handleFileUpload(e.target.files[0])} style={{ display: "none" }} accept=".txt,.pdf" />
                {uploading ? (
                  <><div className="spinner-sm" /><span>Indexing…</span></>
                ) : (
                  <><UploadCloud size={20} className="icon" /><p>Drop PDF / TXT</p><span>or click to browse</span></>
                )}
              </div>

              {/* Indexed Documents */}
              <div className="sidebar-section-header" style={{ marginTop: 4 }}>
                <ChevronRight size={12} /> Indexed Files
              </div>
              {documents.length === 0 ? (
                <div className="no-files-msg">No documents indexed</div>
              ) : (
                documents.map((doc, i) => (
                  <div key={i} className="file-item">
                    <FileText size={14} className="file-icon" />
                    <span className="file-name" title={doc.filename}>{doc.filename}</span>
                    <span className="file-badge">qdrant</span>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>

        {/* Main Editor Area */}
        <div className="main-area">
          {/* Tab Bar */}
          <div className="tab-bar">
            <div className={`tab-item ${activeView === "chat" ? "active" : ""}`} onClick={() => setActiveView("chat")}>
              <MessageSquare size={14} className="tab-icon" />
              Chat Gateway
            </div>
            <div className={`tab-item ${activeView === "metrics" ? "active" : ""}`} onClick={() => setActiveView("metrics")}>
              <BarChart3 size={14} className="tab-icon" />
              Analytics Dashboard
            </div>
          </div>

          {/* Editor Content */}
          <div className="editor-content">

            {/* ===== CHAT VIEW ===== */}
            {activeView === "chat" && (
              <>
                <div className="editor-panel">
                  <div className="chat-messages">
                    {messages.map((msg, i) => (
                      <div key={i} className="message-row">
                        <div className={`message-avatar ${msg.role}`}>
                          {msg.role === "user" ? "Y" : "A"}
                        </div>
                        <div className="message-body">
                          <div className="message-author">
                            {msg.role === "user" ? "You" : "AURA"}
                            <span className="message-timestamp">{timeStr}</span>
                          </div>
                          <div className="message-text">{msg.content}</div>

                          {msg.role === "assistant" && msg.source && msg.source !== "system" && (
                            <div className="message-meta-tags">
                              <span className={`meta-tag ${msg.source === "cache" ? "cache-hit" : "llm-gen"}`}>
                                {msg.source === "cache" ? <><Zap size={10} /> Cache Hit</> : <><Cpu size={10} /> RAG Pipeline</>}
                              </span>
                              <span className="meta-tag latency"><Clock size={10} /> {msg.latency_ms.toFixed(1)}ms</span>
                              {msg.source === "cache" && (
                                <span className="meta-tag similarity">Similarity: {(msg.cache_similarity * 100).toFixed(1)}%</span>
                              )}
                            </div>
                          )}

                          {msg.retrieved_chunks?.length > 0 && (
                            <div className="chunks-container">
                              <div className="chunks-header">Retrieved Chunks</div>
                              {msg.retrieved_chunks.map((c, j) => (
                                <div key={j} className="chunk-item">
                                  <strong>[{c.filename} | score: {c.score.toFixed(3)}]</strong> {c.text.substring(0, 150)}…
                                </div>
                              ))}
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                    {loading && (
                      <div className="message-row">
                        <div className="message-avatar assistant">A</div>
                        <div className="message-body">
                          <div className="message-author">AURA <span className="message-timestamp">typing…</span></div>
                          <div className="typing-indicator"><div className="typing-dot" /><div className="typing-dot" /><div className="typing-dot" /></div>
                        </div>
                      </div>
                    )}
                    <div ref={chatEndRef} />
                  </div>

                  <div className="chat-input-area">
                    <form onSubmit={handleSend} className="chat-form">
                      <input
                        className="chat-input"
                        placeholder="Ask about your documents…"
                        value={query}
                        onChange={(e) => setQuery(e.target.value)}
                        disabled={loading}
                      />
                      <button type="submit" className="btn-send" disabled={!query.trim() || loading}>
                        <Send size={14} />
                      </button>
                    </form>
                  </div>
                </div>

                <div className="resize-handle" />

                {/* Bottom Panel — compact metrics */}
                <div className="bottom-panel">
                  <div className="panel-tabs">
                    <div className={`panel-tab ${activePanel === "metrics" ? "active" : ""}`} onClick={() => setActivePanel("metrics")}>
                      <BarChart3 size={13} /> Metrics
                    </div>
                    <div className={`panel-tab ${activePanel === "evaluations" ? "active" : ""}`} onClick={() => setActivePanel("evaluations")}>
                      <ShieldCheck size={13} /> Evaluations
                    </div>
                    <div className={`panel-tab ${activePanel === "terminal" ? "active" : ""}`} onClick={() => setActivePanel("terminal")}>
                      <Terminal size={13} /> System Log
                    </div>
                  </div>
                  <div className="panel-content">
                    {activePanel === "metrics" && (
                      <div className="stats-grid">
                        <div className="stat-box"><div className="stat-label">Queries</div><div className="stat-value blue">{metrics.summary.total_queries}</div></div>
                        <div className="stat-box"><div className="stat-label">Cache Ratio</div><div className="stat-value green">{(metrics.summary.cache_hit_ratio * 100).toFixed(0)}%</div></div>
                        <div className="stat-box"><div className="stat-label">API Cost</div><div className="stat-value yellow">${metrics.llm_usage.total_cost_usd.toFixed(5)}</div></div>
                        <div className="stat-box"><div className="stat-label">Saved</div><div className="stat-value green">${metrics.llm_usage.saved_cost_usd.toFixed(5)}</div></div>
                      </div>
                    )}
                    {activePanel === "evaluations" && (
                      <div className="eval-logs">
                        {metrics.evaluation_metrics.logs.length === 0 ? <div className="no-files-msg">No audit logs yet.</div> : metrics.evaluation_metrics.logs.map((log, i) => (
                          <div key={i} className="eval-log-entry"><span className="eval-log-prefix">$</span><span className="eval-log-scores"><span className="eval-score faith">F:{log.faithfulness.toFixed(2)}</span><span className="eval-score relev">R:{log.relevance.toFixed(2)}</span></span><span className="eval-log-query" title={log.query}>"{log.query}"</span></div>
                        ))}
                      </div>
                    )}
                    {activePanel === "terminal" && (
                      <div className="eval-logs">
                        <div className="eval-log-entry"><span className="eval-log-prefix">$</span><span style={{ color: "var(--text-primary)" }}>Mode: {metrics.system_status.simulation_mode ? "SIMULATION" : "PRODUCTION"} | Groq: {metrics.system_status.groq_active ? "✓" : "✗"} | Gemini: {metrics.system_status.gemini_active ? "✓" : "✗"}</span></div>
                        <div className="eval-log-entry"><span className="eval-log-prefix">$</span><span style={{ color: "var(--text-primary)" }}>Cache: {metrics.summary.cached_items} items | Hits: {metrics.summary.cache_hits} | Misses: {metrics.summary.cache_misses}</span></div>
                        <div className="eval-log-entry"><span className="eval-log-prefix">$</span><span style={{ color: "var(--text-primary)" }}>Tokens — Primary In: {metrics.llm_usage.primary_input_tokens} Out: {metrics.llm_usage.primary_output_tokens} | Eval In: {metrics.llm_usage.evaluator_input_tokens} Out: {metrics.llm_usage.evaluator_output_tokens}</span></div>
                      </div>
                    )}
                  </div>
                </div>
              </>
            )}

            {/* ===== FULL METRICS VIEW ===== */}
            {activeView === "metrics" && (
              <div className="full-metrics-view">
                <div className="full-metrics-header">
                  <BarChart3 size={16} /> Architecture Analytics
                </div>

                <div className="stats-grid full">
                  <div className="stat-box"><div className="stat-label">Total Queries</div><div className="stat-value blue">{metrics.summary.total_queries}</div></div>
                  <div className="stat-box"><div className="stat-label">Cache Hits</div><div className="stat-value green">{metrics.summary.cache_hits}</div></div>
                  <div className="stat-box"><div className="stat-label">Cache Misses</div><div className="stat-value yellow">{metrics.summary.cache_misses}</div></div>
                  <div className="stat-box"><div className="stat-label">Cache Hit Ratio</div><div className="stat-value green">{(metrics.summary.cache_hit_ratio * 100).toFixed(1)}%</div></div>
                  <div className="stat-box"><div className="stat-label">Cached Items</div><div className="stat-value cyan">{metrics.summary.cached_items}</div></div>
                  <div className="stat-box"><div className="stat-label">API Cost (USD)</div><div className="stat-value yellow">${metrics.llm_usage.total_cost_usd.toFixed(6)}</div></div>
                  <div className="stat-box"><div className="stat-label">Cost Saved (USD)</div><div className="stat-value green">${metrics.llm_usage.saved_cost_usd.toFixed(6)}</div></div>
                  <div className="stat-box"><div className="stat-label">Evaluations Run</div><div className="stat-value purple">{metrics.evaluation_metrics.evaluations_count}</div></div>
                </div>

                <div className="metrics-row">
                  <div className="metrics-section">
                    <div className="metrics-section-title"><TrendingUp size={12} /> Latency Comparison</div>
                    <div className="latency-bars">
                      <div className="latency-row"><span className="latency-label">Cache Hit</span><div className="latency-track"><div className="latency-fill cache" style={{ width: "6%" }} /></div><span className="latency-val">&lt; 10ms</span></div>
                      <div className="latency-row"><span className="latency-label">Groq Inference</span><div className="latency-track"><div className="latency-fill llm" style={{ width: "85%" }} /></div><span className="latency-val">~1,200ms</span></div>
                    </div>
                  </div>
                  <div className="metrics-section">
                    <div className="metrics-section-title"><ShieldCheck size={12} /> Gemini Alignment Judge</div>
                    <div className="gauges-row">
                      {renderGauge(metrics.evaluation_metrics.average_faithfulness, "Faithfulness", "faithfulness")}
                      {renderGauge(metrics.evaluation_metrics.average_relevance, "Relevance", "relevance")}
                    </div>
                  </div>
                </div>

                <div className="full-metrics-section">
                  <div className="metrics-section-title"><Database size={12} /> Token Usage</div>
                  <div className="token-grid">
                    <div className="stat-box"><div className="stat-label">Primary In</div><div className="stat-value blue">{metrics.llm_usage.primary_input_tokens}</div></div>
                    <div className="stat-box"><div className="stat-label">Primary Out</div><div className="stat-value blue">{metrics.llm_usage.primary_output_tokens}</div></div>
                    <div className="stat-box"><div className="stat-label">Evaluator In</div><div className="stat-value purple">{metrics.llm_usage.evaluator_input_tokens}</div></div>
                    <div className="stat-box"><div className="stat-label">Evaluator Out</div><div className="stat-value purple">{metrics.llm_usage.evaluator_output_tokens}</div></div>
                  </div>
                </div>

                <div className="full-metrics-section">
                  <div className="metrics-section-title"><ShieldCheck size={12} /> Evaluation Audit Trail</div>
                  <div className="eval-logs full">
                    {metrics.evaluation_metrics.logs.length === 0 ? <div className="no-files-msg">No evaluation audits logged yet.</div> : metrics.evaluation_metrics.logs.map((log, i) => (
                      <div key={i} className="eval-log-entry"><span className="eval-log-prefix">$</span><span className="eval-log-scores"><span className="eval-score faith">F:{log.faithfulness.toFixed(2)}</span><span className="eval-score relev">R:{log.relevance.toFixed(2)}</span></span><span className="eval-log-query" title={log.query}>"{log.query}"</span></div>
                    ))}
                  </div>
                </div>

                <div className="full-metrics-section">
                  <div className="metrics-section-title"><Terminal size={12} /> System Status</div>
                  <div className="eval-logs">
                    <div className="eval-log-entry"><span className="eval-log-prefix">$</span><span style={{ color: "var(--text-primary)" }}>Mode: {metrics.system_status.simulation_mode ? "SIMULATION" : "PRODUCTION"} | Groq: {metrics.system_status.groq_active ? "✓ Active" : "✗ Inactive"} | Gemini: {metrics.system_status.gemini_active ? "✓ Active" : "✗ Inactive"}</span></div>
                  </div>
                </div>
              </div>
            )}

          </div>
        </div>
      </div>

      {/* Status Bar */}
      <div className={`status-bar ${metrics.system_status.simulation_mode ? "simulation" : ""}`}>
        <div className="status-item">
          <div className={`dot ${metrics.system_status.groq_active ? "online" : "offline"}`} />
          Groq
        </div>
        <div className="status-item">
          <div className={`dot ${metrics.system_status.gemini_active ? "online" : "offline"}`} />
          Gemini
        </div>
        <div className="status-item">
          <Database size={12} /> {metrics.summary.cached_items} cached
        </div>
        <div className="status-spacer" />
        <div className="status-item">
          <DollarSign size={12} /> Cost: ${metrics.llm_usage.total_cost_usd.toFixed(5)}
        </div>
        <button onClick={handleReset} className="btn-reset" title="Reset all data">
          <RefreshCw size={11} /> Reset
        </button>
        <div className="status-item">{metrics.system_status.simulation_mode ? "Simulation" : "Production"}</div>
      </div>
    </div>
  );
}

export default App;
